import {
  BadgePercent,
  Computer,
  Cpu,
  Headphones,
  Laptop,
  MessageCircle,
  Monitor,
  Package,
  Printer,
  Router,
  Settings2,
  ShieldCheck,
  Truck,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  laptop: Laptop,
  computer: Computer,
  monitor: Monitor,
  cpu: Cpu,
  printer: Printer,
  router: Router,
  package: Package,
  wifi: Wifi,
  wrench: Wrench,
  settings: Settings2,
  "message-circle": MessageCircle,
  "shield-check": ShieldCheck,
  truck: Truck,
  "badge-percent": BadgePercent,
  headphones: Headphones,
};
